// Writes dist/client/_headers: security headers for the Cloudflare assets Worker.
//
// The Content-Security-Policy allows scripts from this origin plus the inline
// scripts TanStack Start puts in the prerendered shell, by hash. Those scripts
// contain build-specific values (asset names, a timestamp), so the hashes are
// computed from the built index.html on every build.
//
// Run after `vp build` (see the `build:web` script). Reads VITE_CONVEX_URL from
// the environment, or from .env.local for a local build.
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const OUT = 'dist/client'

if (!process.env.VITE_CONVEX_URL && existsSync('.env.local')) {
  process.loadEnvFile('.env.local')
}
const convexUrl = process.env.VITE_CONVEX_URL
if (!convexUrl) {
  console.error('write-headers: VITE_CONVEX_URL is not set.')
  process.exit(1)
}
const convex = new URL(convexUrl)
const convexWs = `${convex.protocol === 'https:' ? 'wss:' : 'ws:'}//${convex.host}`

const html = readFileSync(`${OUT}/index.html`, 'utf8')
// Hash what the browser hashes: its HTML parser normalises line endings and
// replaces NUL with U+FFFD (the router state in the shell contains a NUL).
const sha256 = (text) => {
  const parsed = text.replace(/\r\n?/g, '\n').replaceAll('\0', '\uFFFD')
  return `'sha256-${createHash('sha256').update(parsed, 'utf8').digest('base64')}'`
}
const inline = (tag) =>
  [
    ...html.matchAll(
      new RegExp(`<${tag}(?![^>]*\\ssrc=)[^>]*>([\\s\\S]*?)</${tag}>`, 'g'),
    ),
  ]
    .map((m) => m[1])
    .filter((body) => body.length > 0)
    .map(sha256)

const csp = [
  "default-src 'self'",
  `script-src 'self' ${inline('script').join(' ')}`,
  ["style-src 'self' https://fonts.googleapis.com", ...inline('style')].join(
    ' ',
  ),
  'font-src https://fonts.gstatic.com',
  "img-src 'self' data:",
  `connect-src 'self' ${convex.origin} ${convexWs}`,
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
].join('; ')

const headers = `# Generated by scripts/write-headers.mjs on every build. Do not edit.
/*
  Content-Security-Policy: ${csp}
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000
  X-Robots-Tag: noindex, nofollow
`

writeFileSync(`${OUT}/_headers`, headers)
console.log(
  `write-headers: ${OUT}/_headers (${inline('script').length} inline script hashes)`,
)
