/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as HostSessionIdRouteImport } from './routes/host.$sessionId'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as PlaySessionIdRouteImport } from './routes/play.$sessionId'
import { Route as AdminQuizzesQuizIdRouteImport } from './routes/admin.quizzes.$quizId'
import { Route as AdminSessionsSessionIdRouteImport } from './routes/admin.sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSessionIdRoute = HostSessionIdRouteImport.update({
  id: '/host/$sessionId',
  path: '/host/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySessionIdRoute = PlaySessionIdRouteImport.update({
  id: '/play/$sessionId',
  path: '/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizzesQuizIdRoute = AdminQuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsSessionIdRoute = AdminSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/host/$sessionId': typeof HostSessionIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/host/$sessionId': typeof HostSessionIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/host': typeof HostIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/host/$sessionId': typeof HostSessionIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/host/': typeof HostIndexRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/admin/sessions/$sessionId': typeof AdminSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/host/$sessionId'
    | '/join/$code'
    | '/play/$sessionId'
    | '/admin/'
    | '/host/'
    | '/admin/quizzes/$quizId'
    | '/admin/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/host/$sessionId'
    | '/join/$code'
    | '/play/$sessionId'
    | '/admin'
    | '/host'
    | '/admin/quizzes/$quizId'
    | '/admin/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/host/$sessionId'
    | '/join/$code'
    | '/play/$sessionId'
    | '/admin/'
    | '/host/'
    | '/admin/quizzes/$quizId'
    | '/admin/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HostSessionIdRoute: typeof HostSessionIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
  PlaySessionIdRoute: typeof PlaySessionIdRoute
  HostIndexRoute: typeof HostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$sessionId': {
      id: '/host/$sessionId'
      path: '/host/$sessionId'
      fullPath: '/host/$sessionId'
      preLoaderRoute: typeof HostSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sessionId': {
      id: '/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof PlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quizzes/$quizId': {
      id: '/admin/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/admin/quizzes/$quizId'
      preLoaderRoute: typeof AdminQuizzesQuizIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/$sessionId': {
      id: '/admin/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/admin/sessions/$sessionId'
      preLoaderRoute: typeof AdminSessionsSessionIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminQuizzesQuizIdRoute: typeof AdminQuizzesQuizIdRoute
  AdminSessionsSessionIdRoute: typeof AdminSessionsSessionIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminQuizzesQuizIdRoute: AdminQuizzesQuizIdRoute,
  AdminSessionsSessionIdRoute: AdminSessionsSessionIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HostSessionIdRoute: HostSessionIdRoute,
  JoinCodeRoute: JoinCodeRoute,
  PlaySessionIdRoute: PlaySessionIdRoute,
  HostIndexRoute: HostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
